name: niraj_portfolio
description: Personal portfolio website for Niraj Vatvani
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0-0

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.5
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  web: ^1.1.0
  animated_text_kit: ^4.2.2
  go_router: ^14.6.2
  gif_view: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/content/shared/
    - assets/content/shared/README.md
    - assets/content/home/
    - assets/content/home/home.md
    - assets/content/about/
    - assets/content/about/about.md
    - assets/content/blog/
    - assets/content/blog/20251217-welcome/
    - assets/content/blog/20251217-welcome/20251217-welcome.md
    - assets/content/blog/20260205-imtgripe/
    - assets/content/blog/20260205-imtgripe/20260205-imtgripe.md