name: niraj_portfolio
description: Personal portfolio website for Niraj Vatvani
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0-0

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.4+3
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  animated_text_kit: ^4.2.2
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/content/shared/
    - assets/content/shared/README.md
    - assets/content/home/
    - assets/content/home/home.md
    - assets/content/about/
    - assets/content/about/about.md
    - assets/content/blog/
    - assets/content/blog/welcome/
    - assets/content/blog/welcome/welcome.md
